### PR TITLE
React to framework/repo rename

### PR DESCRIPTION
**Pull request by henkmollema**
- Renamed tap to `aspnet/dnx`
- Renamed `kvm` to `dnvm`

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@henkmollema__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
Sorry didn't see this PR! I merged https://github.com/aspnet/homebrew-dnx/pull/16 instead.

**Comment by henkmollema** [comment]
Oh well, as long as it's fixed!

**Comment by Eilon** [comment]
I blame my email search :smile: I searched for all GitHub notifications that had "brew" in them but it missed "homebrew" because the search by default is a "startswith" instead of "contains." I'll do a better search next time :smile:

**Comment by henkmollema** [comment]
Ah I see, don't worry about it :smile:

**Pull request closed without merging**
